### ISSUE TITLE
Error: Failed to install 'poolr' from GitHub:

### ISSUE THREAD

**Issue by jazberna1** [ozancinar/poolr#2]
Hello,

I am getting the below error while installing the the development version of the poolr, either with R 3.5.1 or 3.6.3. I was wondering if you could please give some advise to get the package installled.

Thanks so much
Jorge

```
> remotes::install_github("ozancinar/poolr")
Downloading GitHub repo ozancinar/poolr@master
   During startup - Warning message:
   Setting LC_CTYPE failed, using "C" 
v  checking for file '/tmp/Rtmp1xAqu5/remotes7516f6a4f6c/ozancinar-poolr-9c5997a/DESCRIPTION' ...
-  preparing 'poolr':
v  checking DESCRIPTION meta-information ...
-  installing the package to process help pages
-  checking for LF line-endings in source and make files and shell scripts (2.1s)
-  checking for empty or unneeded directories
-  looking to see if a 'data/datalist' file should be added
-  building 'poolr_0.9-8.tar.gz'
   
Installing package into '/mnt/netapp2/uscmg_aplic/4_R_libraries/3_6_3'
(as 'lib' is unspecified)
Error: (converted from warning) Setting LC_CTYPE failed, using "C"
Execution halted
Error: Failed to install 'poolr' from GitHub:
  (converted from warning) installation of package '/tmp/Rtmp1xAqu5/file751651d35809/poolr_0.9-8.tar.gz' had non-zero exit status
```

**Comment by wviechtb** [comment]
Hi Jorge,

I cannot reproduce this. Installation works fine for me.

In your output, I see `Setting LC_CTYPE failed, using "C"`. Googling brought up this: https://stackoverflow.com/q/9689104/2615367. Maybe try some of the solutions discussed there.

**Comment by jazberna1** [comment]
Hi, 

Could you please tell me the R version you use?

Thanks
Jorge

**Comment by wviechtb** [comment]
I am on 4.0.0, but I don't think this is the issue. As far as I can tell from the output, the installation error comes from `Setting LC_CTYPE failed, using "C"` (note that the warning was converted to an error). Googling for this warning/error suggests that this is a MacOS-related issue. Can you install via `install.packages("poolr")`?

**Comment by jazberna1** [comment]
Hello, 

install.packages("poolr") works for me. Would I be fine skipping the developers package?

Thanks
Jorge

**Comment by ozancinar** [comment]
Hello Jorge,

The stable version on CRAN should also work fine. You can see the
changes from the logs in the news document
(https://github.com/ozancinar/poolr/blob/master/NEWS.md). The two
versions are essentially the same, but the stable version may work
slightly slower than the development version.

Best,
ozan


Jorge Zamora <notifications@github.com>, 1 Haz 2020 Pzt, 12:53
tarihinde şunu yazdı:

**Comment by jazberna1** [comment]
Hi Ozan,

Understood!
I'm closing this one.

Thanks
Jorge
